spring:
  application:
    name: courier-management
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/courierdb?useSSL=false&serverTimezone=UTC
    username: postgres
    password: postgres
    
server:
    port: 8081